/**
 * Mapa curricular maestro.
 *
 * Este archivo es deliberadamente "aburrido": contiene datos, no lógica.
 * Mantener el currículo separado de la interfaz permite revisar títulos,
 * conceptos y proyectos sin tocar navegación, estado o componentes visuales.
 */

window.COURSES = [
  {
    "id": 1,
    "name": "FUNDAMENTOS DE INFORMACIÓN",
    "title": "Naturaleza de la información",
    "topics": [
      "Qué entendemos por información.",
      "Diferencia entre información, dato y significado.",
      "Estados físicos.",
      "Estados distinguibles.",
      "Representación.",
      "Interpretación.",
      "Símbolos.",
      "Alfabetos.",
      "Codificación.",
      "Decodificación.",
      "Información física.",
      "Información abstracta.",
      "Relación entre soporte e interpretación.",
      "Sistemas discretos y continuos.",
      "Digitalización.",
      "Qué significa medir información.",
      "Incertidumbre.",
      "Probabilidad.",
      "Sorpresa.",
      "Entropía.",
      "Redundancia.",
      "Compresión.",
      "Límites de la compresión.",
      "Detección de errores.",
      "Corrección de errores.",
      "Información y energía.",
      "Información y computación.",
      "¿Qué es realmente un ordenador?",
      "¿Qué es un bit?",
      "¿Por qué utilizamos dos estados?",
      "¿Qué significa que algo contenga información?",
      "¿Puede destruirse información?",
      "¿Cuánta información contiene un mensaje?"
    ],
    "projects": [],
    "code": "001"
  },
  {
    "id": 2,
    "name": "REPRESENTACIÓN Y SISTEMAS NUMÉRICOS",
    "title": "Sistemas de numeración",
    "topics": [
      "Sistemas posicionales.",
      "Base 2.",
      "Base 8.",
      "Base 10.",
      "Base 16.",
      "Conversión entre bases.",
      "Representación binaria.",
      "Bits, nibbles, bytes y palabras.",
      "Endianness.",
      "Enteros sin signo.",
      "Enteros con signo.",
      "Signo y magnitud.",
      "Complemento a uno.",
      "Complemento a dos.",
      "Overflow.",
      "Underflow.",
      "Extensión de signo.",
      "Aritmética modular.",
      "Operaciones binarias.",
      "Sumas.",
      "Restas.",
      "Multiplicaciones.",
      "Divisiones.",
      "Desplazamientos.",
      "Operaciones bit a bit.",
      "Máscaras de bits.",
      "Punto fijo.",
      "Punto flotante.",
      "IEEE 754.",
      "Exponente y mantisa.",
      "NaN.",
      "Infinito.",
      "Subnormales.",
      "Error numérico.",
      "Redondeo.",
      "Precisión.",
      "Cancelación catastrófica.",
      "ASCII.",
      "Unicode.",
      "UTF-8.",
      "UTF-16.",
      "Imágenes raster.",
      "Color.",
      "RGB.",
      "Alpha.",
      "Audio digital.",
      "Muestreo.",
      "Cuantización.",
      "Formatos binarios.",
      "Serialización."
    ],
    "projects": [],
    "code": "002"
  },
  {
    "id": 3,
    "name": "ELECTRICIDAD PARA INFORMÁTICA",
    "title": "Electricidad fundamental",
    "topics": [
      "Carga eléctrica.",
      "Electrones.",
      "Campo eléctrico.",
      "Potencial eléctrico.",
      "Voltaje.",
      "Corriente.",
      "Resistencia.",
      "Conductancia.",
      "Potencia.",
      "Energía.",
      "Ley de Ohm.",
      "Leyes de Kirchhoff.",
      "Circuitos en serie.",
      "Circuitos en paralelo.",
      "Divisores de tensión.",
      "Fuentes reales e ideales.",
      "Cortocircuitos.",
      "Tierra.",
      "Referencia de potencial.",
      "Resistencias.",
      "Condensadores.",
      "Inductores.",
      "Diodos.",
      "LED.",
      "Transistores.",
      "BJT.",
      "MOSFET.",
      "Semiconductores.",
      "Materiales tipo N y P.",
      "Unión PN.",
      "Ruido.",
      "Capacitancia parásita.",
      "Inductancia parásita.",
      "Tiempo de subida.",
      "Tiempo de bajada.",
      "Retardos.",
      "Consumo.",
      "Calor.",
      "Integridad de señal."
    ],
    "projects": [],
    "code": "003"
  },
  {
    "id": 4,
    "name": "LÓGICA DIGITAL",
    "title": "Álgebra de Boole",
    "topics": [
      "Variables booleanas.",
      "NOT.",
      "AND.",
      "OR.",
      "NAND.",
      "NOR.",
      "XOR.",
      "XNOR.",
      "Tablas de verdad.",
      "Expresiones booleanas.",
      "Leyes de De Morgan.",
      "Simplificación lógica.",
      "Mapas de Karnaugh.",
      "Lógica combinacional.",
      "Universalidad de NAND y NOR.",
      "Multiplexores.",
      "Demultiplexores.",
      "Codificadores.",
      "Decodificadores.",
      "Comparadores.",
      "Half adder.",
      "Full adder.",
      "Sumadores.",
      "Restadores.",
      "ALU.",
      "Realimentación.",
      "Latches.",
      "Flip-flops.",
      "SR.",
      "D.",
      "JK.",
      "T.",
      "Registros.",
      "Contadores.",
      "Máquinas de estados.",
      "Relojes.",
      "Frecuencia.",
      "Ciclo de reloj.",
      "Setup time.",
      "Hold time.",
      "Metastabilidad.",
      "Sincronización.",
      "SRAM.",
      "DRAM.",
      "ROM.",
      "EEPROM.",
      "Flash."
    ],
    "projects": [],
    "code": "004"
  },
  {
    "id": 5,
    "name": "ARQUITECTURA DE COMPUTADORES",
    "title": "Organización básica de un computador",
    "topics": [
      "Modelo de Von Neumann.",
      "Modelo Harvard.",
      "CPU.",
      "Memoria.",
      "Entrada/salida.",
      "Buses.",
      "Bus de datos.",
      "Bus de direcciones.",
      "Bus de control.",
      "Ciclo fetch-decode-execute.",
      "Unidad de control.",
      "ALU.",
      "Registros.",
      "Program counter.",
      "Stack pointer.",
      "Flags.",
      "Instruction register.",
      "Decodificador de instrucciones.",
      "Datapath.",
      "Microarquitectura.",
      "Qué es una ISA.",
      "Opcode.",
      "Operandos.",
      "Modos de direccionamiento.",
      "Instrucciones aritméticas.",
      "Instrucciones lógicas.",
      "Saltos.",
      "Llamadas.",
      "Retornos.",
      "Load/store.",
      "Privilegios.",
      "x86.",
      "x86-64.",
      "ARM.",
      "AArch64.",
      "RISC-V.",
      "CISC.",
      "RISC."
    ],
    "projects": [],
    "code": "005"
  },
  {
    "id": 6,
    "name": "ASSEMBLY",
    "title": "Programación de bajo nivel",
    "topics": [
      "Registros.",
      "Movimiento de datos.",
      "Operaciones aritméticas.",
      "Operaciones lógicas.",
      "Saltos.",
      "Comparaciones.",
      "Loops.",
      "Stack.",
      "Calls.",
      "Return.",
      "Calling conventions.",
      "Syscalls.",
      "Assembly x86-64.",
      "Assembly ARM.",
      "Assembly RISC-V.",
      "Debugging de assembly.",
      "Desensamblado.",
      "Lectura de código generado por compiladores."
    ],
    "projects": [],
    "code": "006"
  },
  {
    "id": 7,
    "name": "MICROARQUITECTURA AVANZADA",
    "title": "Cómo una CPU ejecuta realmente instrucciones",
    "topics": [
      "Pipeline.",
      "Etapas del pipeline.",
      "Hazards.",
      "Data hazards.",
      "Control hazards.",
      "Structural hazards.",
      "Forwarding.",
      "Stalling.",
      "Branch prediction.",
      "Predicción dinámica.",
      "Ejecución especulativa.",
      "Ejecución fuera de orden.",
      "Register renaming.",
      "Reorder buffer.",
      "Superscalar.",
      "ILP.",
      "Micro-ops.",
      "Microcode.",
      "Retiro de instrucciones.",
      "IPC.",
      "CPI.",
      "Latencia.",
      "Throughput.",
      "Ley de Amdahl.",
      "Benchmarking."
    ],
    "projects": [],
    "code": "007"
  },
  {
    "id": 8,
    "name": "JERARQUÍA DE MEMORIA",
    "title": "Memoria y almacenamiento",
    "topics": [
      "Registros.",
      "Caché.",
      "L1.",
      "L2.",
      "L3.",
      "Cache lines.",
      "Localidad temporal.",
      "Localidad espacial.",
      "Cache hit.",
      "Cache miss.",
      "Associativity.",
      "Replacement policies.",
      "Write-through.",
      "Write-back.",
      "Coherencia de caché.",
      "MESI.",
      "False sharing.",
      "RAM.",
      "DRAM.",
      "Controlador de memoria.",
      "Canales de memoria.",
      "Latencia.",
      "Ancho de banda.",
      "NUMA.",
      "Direcciones virtuales.",
      "Direcciones físicas.",
      "MMU.",
      "Page tables.",
      "Páginas.",
      "Page faults.",
      "TLB.",
      "Huge pages.",
      "Protección de memoria.",
      "HDD.",
      "SSD.",
      "NAND flash.",
      "Bloques.",
      "Páginas.",
      "Wear leveling.",
      "Controladores.",
      "NVMe."
    ],
    "projects": [],
    "code": "008"
  },
  {
    "id": 9,
    "name": "PROGRAMACIÓN DE SISTEMAS",
    "title": "C profundo",
    "topics": [
      "Modelo de memoria de C.",
      "Variables.",
      "Punteros.",
      "Arrays.",
      "Pointer arithmetic.",
      "Structs.",
      "Unions.",
      "Alignment.",
      "Padding.",
      "Const.",
      "Volatile.",
      "Undefined behaviour.",
      "Implementation-defined behaviour.",
      "Memory aliasing.",
      "Strict aliasing.",
      "Bitfields.",
      "Function pointers.",
      "Callbacks.",
      "Macros.",
      "Preprocesador.",
      "Stack.",
      "Heap.",
      "Static storage.",
      "Globales.",
      "Lifetime.",
      "Scope.",
      "Allocations.",
      "Fragmentación.",
      "malloc.",
      "calloc.",
      "realloc.",
      "free."
    ],
    "projects": [
      "Crear un allocator propio."
    ],
    "code": "009"
  },
  {
    "id": 10,
    "name": "COMPILADORES Y LENGUAJES",
    "title": "Cómo un programa se convierte en máquina",
    "topics": [
      "Preprocesado.",
      "Compilación.",
      "Assembly.",
      "Ensamblado.",
      "Linking.",
      "Static linking.",
      "Dynamic linking.",
      "Object files.",
      "Symbols.",
      "Relocations.",
      "ELF.",
      "PE.",
      "Executables.",
      "Shared libraries.",
      "Loader.",
      "Tokens.",
      "Lexer.",
      "Parser.",
      "Gramáticas.",
      "AST.",
      "Semántica.",
      "Type checking.",
      "Intermediate representation.",
      "Optimización.",
      "Code generation.",
      "Bytecode.",
      "Máquinas virtuales.",
      "JIT."
    ],
    "projects": [
      "Lenguaje propio.",
      "Intérprete.",
      "Compilador pequeño.",
      "Máquina virtual."
    ],
    "code": "010"
  },
  {
    "id": 11,
    "name": "DEBUGGING Y ANÁLISIS DE PROGRAMAS",
    "title": "Entender programas en ejecución",
    "topics": [
      "GDB.",
      "LLDB.",
      "Breakpoints.",
      "Watchpoints.",
      "Registers.",
      "Stack traces.",
      "Core dumps.",
      "Memory maps.",
      "strace.",
      "ltrace.",
      "Valgrind.",
      "Sanitizers.",
      "Profilers.",
      "Perf.",
      "Debug symbols.",
      "DWARF."
    ],
    "projects": [],
    "code": "011"
  },
  {
    "id": 12,
    "name": "SISTEMAS OPERATIVOS",
    "title": "Fundamentos de sistemas operativos",
    "topics": [
      "Qué problema resuelve un sistema operativo.",
      "Kernel.",
      "User space.",
      "Kernel space.",
      "Ring levels.",
      "Privilegios.",
      "Boot.",
      "BIOS.",
      "UEFI.",
      "Bootloader.",
      "Inicialización del kernel.",
      "Process.",
      "Thread.",
      "PCB.",
      "Context switch.",
      "Scheduler.",
      "Preemption.",
      "Scheduling algorithms.",
      "Prioridades.",
      "Multitasking.",
      "Entrada al kernel.",
      "API.",
      "ABI.",
      "Syscall interface.",
      "Pipes.",
      "Signals.",
      "Shared memory.",
      "Message queues.",
      "Sockets.",
      "Semaphores.",
      "Race conditions.",
      "Locks.",
      "Mutexes.",
      "Semaphores.",
      "Condition variables.",
      "Atomics.",
      "Deadlock.",
      "Livelock.",
      "Starvation."
    ],
    "projects": [],
    "code": "012"
  },
  {
    "id": 13,
    "name": "SISTEMAS DE ARCHIVOS",
    "title": "Almacenamiento organizado",
    "topics": [
      "Files.",
      "Directories.",
      "Metadata.",
      "Inodes.",
      "File descriptors.",
      "Blocks.",
      "Journaling.",
      "Permissions.",
      "Mounting.",
      "VFS.",
      "ext4.",
      "FAT.",
      "NTFS.",
      "Copy-on-write.",
      "ZFS/Btrfs.",
      "Caching."
    ],
    "projects": [
      "Crear un sistema de archivos educativo."
    ],
    "code": "013"
  },
  {
    "id": 14,
    "name": "DRIVERS Y HARDWARE",
    "title": "Comunicación entre sistema operativo y dispositivos",
    "topics": [
      "Device drivers.",
      "MMIO.",
      "Port-mapped I/O.",
      "Interrupts.",
      "IRQ.",
      "DMA.",
      "PCI.",
      "PCI Express.",
      "USB.",
      "HID.",
      "Drivers de almacenamiento.",
      "Drivers gráficos.",
      "Drivers de red."
    ],
    "projects": [],
    "code": "014"
  },
  {
    "id": 15,
    "name": "LINUX INTERNO",
    "title": "Linux desde dentro",
    "topics": [
      "Kernel Linux.",
      "Procesos.",
      "/proc.",
      "/sys.",
      "/dev.",
      "System calls.",
      "Namespaces.",
      "cgroups.",
      "Containers.",
      "systemd.",
      "Signals.",
      "Permissions.",
      "Capabilities.",
      "SELinux/AppArmor.",
      "Modules del kernel.",
      "eBPF."
    ],
    "projects": [
      "Shell propia.",
      "Herramientas tipo Unix.",
      "Kernel educativo."
    ],
    "code": "015"
  },
  {
    "id": 16,
    "name": "REDES FÍSICAS",
    "title": "Cómo viajan realmente los bits",
    "topics": [
      "Señales eléctricas.",
      "Señales ópticas.",
      "Radio.",
      "Modulación.",
      "Codificación de línea.",
      "Ruido.",
      "SNR.",
      "Atenuación.",
      "Ancho de banda.",
      "Latencia.",
      "Fibra óptica.",
      "Cableado.",
      "Wi-Fi.",
      "Ethernet físico."
    ],
    "projects": [],
    "code": "016"
  },
  {
    "id": 17,
    "name": "ETHERNET Y REDES LOCALES",
    "title": "Layer 2",
    "topics": [
      "Frames.",
      "MAC addresses.",
      "Ethernet.",
      "Switches.",
      "Learning tables.",
      "Broadcast.",
      "Collision domains.",
      "VLAN.",
      "ARP.",
      "Spanning Tree.",
      "MTU."
    ],
    "projects": [],
    "code": "017"
  },
  {
    "id": 18,
    "name": "INTERNET PROTOCOL",
    "title": "IP",
    "topics": [
      "IPv4.",
      "IPv6.",
      "Direcciones IP.",
      "Subredes.",
      "Máscaras.",
      "CIDR.",
      "Gateway.",
      "Routing.",
      "Routing tables.",
      "TTL.",
      "ICMP.",
      "Fragmentación.",
      "NAT.",
      "DHCP."
    ],
    "projects": [],
    "code": "018"
  },
  {
    "id": 19,
    "name": "ROUTING E INTERNET GLOBAL",
    "title": "Cómo funciona Internet",
    "topics": [
      "Routers.",
      "Sistemas autónomos.",
      "BGP.",
      "Peering.",
      "Transit.",
      "IXPs.",
      "Backbone.",
      "Routing global.",
      "Anycast.",
      "CDN.",
      "Load balancing.",
      "Data centers."
    ],
    "projects": [],
    "code": "019"
  },
  {
    "id": 20,
    "name": "TRANSPORTE",
    "title": "TCP y UDP",
    "topics": [
      "Ports.",
      "Sockets.",
      "UDP.",
      "TCP.",
      "Three-way handshake.",
      "Sequence numbers.",
      "ACK.",
      "Retransmisión.",
      "Sliding windows.",
      "Flow control.",
      "Congestion control.",
      "Slow start.",
      "RTT.",
      "Packet loss.",
      "QUIC."
    ],
    "projects": [],
    "code": "020"
  },
  {
    "id": 21,
    "name": "PROTOCOLOS DE APLICACIÓN",
    "title": "Internet visible",
    "topics": [
      "DNS.",
      "HTTP.",
      "HTTP/1.1.",
      "HTTP/2.",
      "HTTP/3.",
      "URLs.",
      "Headers.",
      "Cookies.",
      "Sessions.",
      "Cache.",
      "Proxies.",
      "Reverse proxies.",
      "SMTP.",
      "IMAP.",
      "FTP.",
      "SSH.",
      "WebSockets."
    ],
    "projects": [
      "Servidor HTTP.",
      "Cliente HTTP.",
      "DNS básico.",
      "Analizador de paquetes.",
      "Simulador de red."
    ],
    "code": "021"
  },
  {
    "id": 22,
    "name": "CRIPTOGRAFÍA",
    "title": "Fundamentos criptográficos",
    "topics": [
      "Amenazas.",
      "Confidencialidad.",
      "Integridad.",
      "Autenticidad.",
      "Entropía.",
      "Randomness.",
      "PRNG.",
      "Hashes.",
      "SHA.",
      "MAC.",
      "HMAC.",
      "Cifrado simétrico.",
      "AES.",
      "Modos de operación.",
      "Cifrado asimétrico.",
      "RSA.",
      "Diffie-Hellman.",
      "Curvas elípticas.",
      "Firmas digitales.",
      "Certificados.",
      "PKI.",
      "TLS.",
      "Perfect forward secrecy.",
      "Password hashing.",
      "Salt.",
      "KDF."
    ],
    "projects": [],
    "code": "022"
  },
  {
    "id": 23,
    "name": "CIBERSEGURIDAD DE SISTEMAS",
    "title": "Seguridad fundamental",
    "topics": [
      "Threat modeling.",
      "Attack surface.",
      "Privilege.",
      "Least privilege.",
      "Authentication.",
      "Authorization.",
      "Access control.",
      "Linux permissions.",
      "SUID.",
      "Capabilities.",
      "Sandboxing.",
      "Containers.",
      "Isolation."
    ],
    "projects": [],
    "code": "023"
  },
  {
    "id": 24,
    "name": "SEGURIDAD WEB",
    "title": "Explotación de aplicaciones web",
    "topics": [
      "HTTP profundo.",
      "Cookies.",
      "Sessions.",
      "Same-origin policy.",
      "CORS.",
      "Authentication bugs.",
      "SQL injection.",
      "Command injection.",
      "XSS.",
      "CSRF.",
      "SSRF.",
      "Path traversal.",
      "File inclusion.",
      "File upload.",
      "IDOR.",
      "XXE.",
      "Deserialization.",
      "Race conditions.",
      "JWT.",
      "OAuth.",
      "Access control vulnerabilities.",
      "OverTheWire.",
      "Natas.",
      "PortSwigger Web Security Academy.",
      "PicoCTF."
    ],
    "projects": [],
    "code": "024"
  },
  {
    "id": 25,
    "name": "EXPLOTACIÓN BINARIA",
    "title": "Binary exploitation",
    "topics": [
      "Stack frames.",
      "Buffer overflow.",
      "Stack smashing.",
      "Return addresses.",
      "Shellcode.",
      "NX.",
      "ASLR.",
      "PIE.",
      "Stack canaries.",
      "RELRO.",
      "GOT.",
      "PLT.",
      "ret2libc.",
      "ROP.",
      "Format strings.",
      "Heap exploitation.",
      "Use-after-free.",
      "Double free.",
      "Integer overflow.",
      "Type confusion."
    ],
    "projects": [],
    "code": "025"
  },
  {
    "id": 26,
    "name": "REVERSE ENGINEERING",
    "title": "Ingeniería inversa",
    "topics": [
      "Assembly avanzado.",
      "Disassemblers.",
      "Decompilers.",
      "Ghidra.",
      "Binary Ninja/IDA conceptualmente.",
      "Control flow.",
      "Data flow.",
      "Calling conventions.",
      "Compiler patterns.",
      "Stripped binaries.",
      "Packers.",
      "Obfuscation.",
      "Anti-debugging.",
      "Firmware reversing."
    ],
    "projects": [],
    "code": "026"
  },
  {
    "id": 27,
    "name": "MALWARE Y FORENSE",
    "title": "Análisis defensivo",
    "topics": [
      "Malware architecture.",
      "Persistencia.",
      "Evasión.",
      "Análisis estático.",
      "Análisis dinámico.",
      "Sandboxes.",
      "Memory forensics.",
      "Disk forensics.",
      "Network forensics.",
      "Logs.",
      "Incident response.",
      "IOC.",
      "YARA.",
      "Volatility."
    ],
    "projects": [],
    "code": "027"
  },
  {
    "id": 28,
    "name": "MATEMÁTICAS DISCRETAS",
    "title": "Matemática de la computación",
    "topics": [
      "Lógica.",
      "Conjuntos.",
      "Relaciones.",
      "Funciones.",
      "Combinatoria.",
      "Permutaciones.",
      "Combinaciones.",
      "Recurrencias.",
      "Inducción.",
      "Grafos.",
      "Árboles.",
      "Autómatas.",
      "Lenguajes formales."
    ],
    "projects": [],
    "code": "028"
  },
  {
    "id": 29,
    "name": "ÁLGEBRA LINEAL",
    "title": "Vectores y matrices",
    "topics": [
      "Vectores.",
      "Matrices.",
      "Sistemas lineales.",
      "Producto escalar.",
      "Producto vectorial.",
      "Bases.",
      "Espacios vectoriales.",
      "Transformaciones lineales.",
      "Determinante.",
      "Inversa.",
      "Eigenvalues.",
      "Eigenvectors.",
      "SVD.",
      "Normas.",
      "Proyecciones.",
      "Gráficos.",
      "Física.",
      "IA.",
      "Procesamiento de señales."
    ],
    "projects": [],
    "code": "029"
  },
  {
    "id": 30,
    "name": "CÁLCULO",
    "title": "Cambio continuo",
    "topics": [
      "Límites.",
      "Derivadas.",
      "Integrales.",
      "Series.",
      "Cálculo multivariable.",
      "Derivadas parciales.",
      "Gradiente.",
      "Jacobiano.",
      "Hessiano.",
      "Ecuaciones diferenciales."
    ],
    "projects": [],
    "code": "030"
  },
  {
    "id": 31,
    "name": "PROBABILIDAD Y ESTADÍSTICA",
    "title": "Incertidumbre matemática",
    "topics": [
      "Variables aleatorias.",
      "Distribuciones.",
      "Esperanza.",
      "Varianza.",
      "Covarianza.",
      "Probabilidad condicionada.",
      "Bayes.",
      "Gaussianas.",
      "Estimación.",
      "Muestreo.",
      "Intervalos.",
      "Hipótesis.",
      "Correlación.",
      "Regresión."
    ],
    "projects": [],
    "code": "031"
  },
  {
    "id": 32,
    "name": "OPTIMIZACIÓN",
    "title": "Encontrar buenas soluciones",
    "topics": [
      "Funciones de coste.",
      "Convexidad.",
      "Gradiente descendente.",
      "SGD.",
      "Momentum.",
      "Newton.",
      "Restricciones.",
      "Lagrange.",
      "Optimización combinatoria.",
      "Optimización numérica."
    ],
    "projects": [],
    "code": "032"
  },
  {
    "id": 33,
    "name": "SEÑALES Y FFT",
    "title": "Procesamiento de señales",
    "topics": [
      "Señales continuas.",
      "Señales discretas.",
      "Frecuencia.",
      "Fase.",
      "Fourier.",
      "Transformada de Fourier.",
      "DFT.",
      "FFT.",
      "Convolución.",
      "Filtrado.",
      "Sampling.",
      "Aliasing.",
      "Nyquist-Shannon.",
      "Espectros.",
      "Audio.",
      "Imagen.",
      "Telecomunicaciones.",
      "Demoscene.",
      "IA."
    ],
    "projects": [],
    "code": "033"
  },
  {
    "id": 34,
    "name": "GRÁFICOS POR ORDENADOR",
    "title": "Fundamentos gráficos",
    "topics": [
      "Píxeles.",
      "Framebuffers.",
      "Resolución.",
      "Color.",
      "Coordenadas.",
      "Vectores.",
      "Matrices.",
      "Espacios de coordenadas.",
      "Transformaciones.",
      "Model.",
      "View.",
      "Projection.",
      "Cámara.",
      "Perspectiva.",
      "Clipping.",
      "Rasterización.",
      "Triángulos.",
      "Interpolación.",
      "Z-buffer.",
      "Texturas.",
      "Sampling.",
      "Filtering."
    ],
    "projects": [],
    "code": "034"
  },
  {
    "id": 35,
    "name": "GPU",
    "title": "Arquitectura gráfica",
    "topics": [
      "CPU frente a GPU.",
      "SIMD.",
      "SIMT.",
      "Warps/wavefronts.",
      "GPU cores.",
      "Memory hierarchy.",
      "VRAM.",
      "Texture units.",
      "Rasterizer.",
      "Compute.",
      "Parallelism.",
      "Divergence.",
      "GPU caches."
    ],
    "projects": [],
    "code": "035"
  },
  {
    "id": 36,
    "name": "SHADERS Y APIs GRÁFICAS",
    "title": "Programación gráfica",
    "topics": [
      "Vertex shaders.",
      "Fragment shaders.",
      "Compute shaders.",
      "GLSL.",
      "SPIR-V.",
      "OpenGL.",
      "Vulkan.",
      "Pipeline gráfico.",
      "Buffers.",
      "Textures.",
      "Uniforms.",
      "Descriptor sets.",
      "Render passes.",
      "Synchronization."
    ],
    "projects": [],
    "code": "036"
  },
  {
    "id": 37,
    "name": "ILUMINACIÓN Y RENDER",
    "title": "Producción de imágenes",
    "topics": [
      "Luz.",
      "Reflectancia.",
      "Lambert.",
      "Phong.",
      "Blinn-Phong.",
      "BRDF.",
      "PBR.",
      "Normal mapping.",
      "Shadows.",
      "Shadow maps.",
      "Ambient occlusion.",
      "HDR.",
      "Tone mapping.",
      "Global illumination.",
      "Ray tracing.",
      "Path tracing.",
      "Monte Carlo."
    ],
    "projects": [],
    "code": "037"
  },
  {
    "id": 38,
    "name": "MOTOR GRÁFICO",
    "title": "Construcción de un renderer",
    "topics": [
      "Scene graph.",
      "Resource management.",
      "Materials.",
      "Meshes.",
      "Cameras.",
      "Lighting.",
      "Visibility.",
      "Culling.",
      "LOD.",
      "Batching.",
      "Instancing.",
      "Post-processing."
    ],
    "projects": [
      "Crear un motor gráfico propio."
    ],
    "code": "038"
  },
  {
    "id": 39,
    "name": "ARQUITECTURA DE VIDEOJUEGOS",
    "title": "Game engine architecture",
    "topics": [
      "Game loop.",
      "Fixed timestep.",
      "Variable timestep.",
      "ECS.",
      "Component systems.",
      "Scene management.",
      "Resource systems.",
      "Event systems.",
      "Input.",
      "Serialization.",
      "Save games."
    ],
    "projects": [],
    "code": "039"
  },
  {
    "id": 40,
    "name": "FÍSICA DE VIDEOJUEGOS",
    "title": "Simulación",
    "topics": [
      "Cinemática.",
      "Dinámica.",
      "Integración numérica.",
      "Euler.",
      "Verlet.",
      "Rigid bodies.",
      "Collision detection.",
      "Broad phase.",
      "Narrow phase.",
      "Impulses.",
      "Constraints.",
      "Friction.",
      "Joints."
    ],
    "projects": [],
    "code": "040"
  },
  {
    "id": 41,
    "name": "ANIMACIÓN",
    "title": "Animación digital",
    "topics": [
      "Keyframes.",
      "Interpolación.",
      "Skeletal animation.",
      "Bones.",
      "Skinning.",
      "Forward kinematics.",
      "Inverse kinematics.",
      "Animation blending.",
      "State machines."
    ],
    "projects": [],
    "code": "041"
  },
  {
    "id": 42,
    "name": "IA PARA VIDEOJUEGOS",
    "title": "Sistemas de comportamiento",
    "topics": [
      "Finite state machines.",
      "Behaviour trees.",
      "Utility AI.",
      "Steering.",
      "A\\*.",
      "Pathfinding.",
      "Navigation meshes.",
      "Procedural behaviour."
    ],
    "projects": [],
    "code": "042"
  },
  {
    "id": 43,
    "name": "AUDIO PARA VIDEOJUEGOS",
    "title": "Audio interactivo",
    "topics": [
      "Digital audio.",
      "Mixing.",
      "Sampling.",
      "DSP.",
      "Spatial audio.",
      "Doppler.",
      "Reverb.",
      "Procedural audio.",
      "Music systems."
    ],
    "projects": [],
    "code": "043"
  },
  {
    "id": 44,
    "name": "NETWORKING DE VIDEOJUEGOS",
    "title": "Juegos multijugador",
    "topics": [
      "Client/server.",
      "P2P.",
      "Tick rate.",
      "Snapshot interpolation.",
      "Prediction.",
      "Reconciliation.",
      "Lag compensation.",
      "Rollback.",
      "Determinismo.",
      "Replicación de estados."
    ],
    "projects": [],
    "code": "044"
  },
  {
    "id": 45,
    "name": "GODOT PROFUNDO",
    "title": "Motor Godot",
    "topics": [
      "Arquitectura interna.",
      "Scene tree.",
      "Nodes.",
      "Resources.",
      "Signals.",
      "Rendering.",
      "Physics.",
      "Input.",
      "Scripting.",
      "GDScript.",
      "C#.",
      "GDExtension.",
      "Profiling.",
      "Networking.",
      "Editor tools.",
      "Custom nodes.",
      "Engine source."
    ],
    "projects": [],
    "code": "045"
  },
  {
    "id": 46,
    "name": "PIXEL ART Y ARTE TÉCNICO",
    "title": "Representación visual discreta",
    "topics": [
      "Pixel clusters.",
      "Silueta.",
      "Paletas.",
      "Color.",
      "Dithering.",
      "Antialiasing manual.",
      "Subpixel animation.",
      "Tilesets.",
      "Sprites.",
      "Animation.",
      "Pixel-perfect rendering.",
      "Procedural pixel art."
    ],
    "projects": [],
    "code": "046"
  },
  {
    "id": 47,
    "name": "DEMOSCENE: HISTORIA Y CULTURA",
    "title": "Demoscene",
    "topics": [
      "Origen de la demoscene.",
      "Crack intros.",
      "Commodore 64.",
      "Amiga.",
      "Atari.",
      "PC demo scene.",
      "Future Crew.",
      "Second Reality.",
      "Assembly.",
      "The Black Lotus.",
      "Farbrausch.",
      "Conspiracy.",
      "Scene.org.",
      "Demo parties.",
      "Competitions."
    ],
    "projects": [],
    "code": "047"
  },
  {
    "id": 48,
    "name": "EFECTOS CLÁSICOS DE DEMOSCENE",
    "title": "Efectos",
    "topics": [
      "Plasma.",
      "Fire.",
      "Tunnel.",
      "Starfields.",
      "Scrollers.",
      "Copper effects.",
      "Rotozoom.",
      "Metaballs.",
      "Water.",
      "Feedback.",
      "Palette cycling.",
      "Fractals.",
      "Voxels.",
      "Heightmaps.",
      "Bump mapping."
    ],
    "projects": [],
    "code": "048"
  },
  {
    "id": 49,
    "name": "SIZECODING",
    "title": "Programar bajo límites extremos",
    "topics": [
      "256-byte intros.",
      "1 KB intros.",
      "4 KB intros.",
      "64 KB intros.",
      "Assembly extremo.",
      "Binary size.",
      "Compressors.",
      "Executable structure.",
      "Code/data dual use.",
      "Procedural generation.",
      "Shader compression.",
      "Synthesizers procedurales.",
      "Entropy coding.",
      "Arquitecturas orientadas a tamaño."
    ],
    "projects": [],
    "code": "049"
  },
  {
    "id": 50,
    "name": "RAYMARCHING Y SHADER ART",
    "title": "Gráficos procedurales",
    "topics": [
      "Signed distance fields.",
      "Raymarching.",
      "Sphere tracing.",
      "CSG.",
      "Normals.",
      "Lighting.",
      "Soft shadows.",
      "Ambient occlusion.",
      "Fractals.",
      "Domain repetition.",
      "Noise.",
      "Procedural textures."
    ],
    "projects": [],
    "code": "050"
  },
  {
    "id": 51,
    "name": "MÚSICA PROCEDURAL",
    "title": "Síntesis",
    "topics": [
      "Osciladores.",
      "Ondas.",
      "ADSR.",
      "Filtros.",
      "LFO.",
      "FM.",
      "Subtractive synthesis.",
      "Sequencers.",
      "Tracker music.",
      "Procedural music.",
      "Tiny synthesizers."
    ],
    "projects": [],
    "code": "051"
  },
  {
    "id": 52,
    "name": "ELECTRÓNICA ANALÓGICA",
    "title": "Circuitos reales",
    "topics": [
      "Amplificadores.",
      "Op-amps.",
      "Filtros.",
      "Osciladores.",
      "Reguladores.",
      "ADC.",
      "DAC.",
      "Fuentes.",
      "Señal.",
      "Ruido.",
      "Instrumentación."
    ],
    "projects": [],
    "code": "052"
  },
  {
    "id": 53,
    "name": "MICROCONTROLADORES",
    "title": "Computación embebida",
    "topics": [
      "Arduino interno.",
      "AVR.",
      "STM32.",
      "ARM Cortex-M.",
      "GPIO.",
      "Timers.",
      "PWM.",
      "Interrupts.",
      "ADC.",
      "DAC.",
      "UART.",
      "SPI.",
      "I²C.",
      "DMA.",
      "Watchdogs.",
      "Bare metal.",
      "Bootloaders.",
      "Real-time programming."
    ],
    "projects": [],
    "code": "053"
  },
  {
    "id": 54,
    "name": "SISTEMAS EMBEBIDOS",
    "title": "Hardware + software",
    "topics": [
      "RTOS.",
      "Scheduling.",
      "Memory constraints.",
      "Power management.",
      "Sensors.",
      "Actuators.",
      "Motor control.",
      "Communication buses.",
      "Reliability."
    ],
    "projects": [],
    "code": "054"
  },
  {
    "id": 55,
    "name": "FPGA",
    "title": "Diseñar hardware programable",
    "topics": [
      "HDL.",
      "Verilog/SystemVerilog.",
      "VHDL conceptualmente.",
      "Combinational logic.",
      "Sequential logic.",
      "Clock domains.",
      "Timing.",
      "Synthesis.",
      "Place and route.",
      "FPGA architecture.",
      "BRAM.",
      "DSP blocks.",
      "PLL.",
      "Soft CPUs."
    ],
    "projects": [
      "ALU.",
      "CPU.",
      "Controlador de vídeo.",
      "Hardware gráfico sencillo."
    ],
    "code": "055"
  },
  {
    "id": 56,
    "name": "PCB",
    "title": "Diseño electrónico físico",
    "topics": [
      "Schematics.",
      "PCB layout.",
      "Traces.",
      "Layers.",
      "Ground planes.",
      "Decoupling.",
      "Power integrity.",
      "Signal integrity.",
      "Differential pairs.",
      "Impedance.",
      "EMC.",
      "Connectors.",
      "Manufacturing.",
      "Soldering.",
      "Debugging físico."
    ],
    "projects": [],
    "code": "056"
  },
  {
    "id": 57,
    "name": "ALGORITMOS Y ESTRUCTURAS DE DATOS",
    "title": "Organización eficiente de información",
    "topics": [
      "Complejidad temporal.",
      "Complejidad espacial.",
      "Big O.",
      "Arrays.",
      "Linked lists.",
      "Stacks.",
      "Queues.",
      "Hash tables.",
      "Trees.",
      "Binary search trees.",
      "Heaps.",
      "Tries.",
      "Graphs.",
      "Sorting.",
      "Searching.",
      "Dynamic programming.",
      "Greedy algorithms.",
      "Graph algorithms."
    ],
    "projects": [],
    "code": "057"
  },
  {
    "id": 58,
    "name": "TEORÍA DE LA COMPUTACIÓN",
    "title": "Límites de las máquinas",
    "topics": [
      "Autómatas finitos.",
      "Máquinas de Turing.",
      "Computabilidad.",
      "Decidibilidad.",
      "Halting problem.",
      "Reductions.",
      "Complexity classes.",
      "P.",
      "NP.",
      "NP-completeness.",
      "Problemas intratables."
    ],
    "projects": [],
    "code": "058"
  },
  {
    "id": 59,
    "name": "CONCURRENCIA Y PARALELISMO",
    "title": "Computación simultánea",
    "topics": [
      "Threads.",
      "Processes.",
      "Parallelism.",
      "Concurrency.",
      "Locks.",
      "Atomics.",
      "Lock-free.",
      "Memory ordering.",
      "Memory models.",
      "SIMD.",
      "GPU parallelism.",
      "Distributed parallelism."
    ],
    "projects": [],
    "code": "059"
  },
  {
    "id": 60,
    "name": "INTELIGENCIA ARTIFICIAL: FUNDAMENTOS",
    "title": "Aprender desde las matemáticas",
    "topics": [
      "Qué significa aprender.",
      "Funciones.",
      "Parámetros.",
      "Modelos.",
      "Loss functions.",
      "Optimización.",
      "Dataset.",
      "Train/test.",
      "Overfitting.",
      "Generalization."
    ],
    "projects": [],
    "code": "060"
  },
  {
    "id": 61,
    "name": "REDES NEURONALES DESDE CERO",
    "title": "Neural networks",
    "topics": [
      "Neurona artificial.",
      "Perceptrón.",
      "Activaciones.",
      "Redes multicapa.",
      "Forward pass.",
      "Loss.",
      "Derivadas.",
      "Chain rule.",
      "Backpropagation.",
      "Gradient descent.",
      "Initialization.",
      "Regularization.",
      "Batch normalization.",
      "Optimizers."
    ],
    "projects": [
      "Red neuronal sin frameworks.",
      "Después red neuronal usando NumPy."
    ],
    "code": "061"
  },
  {
    "id": 62,
    "name": "DEEP LEARNING",
    "title": "Arquitecturas modernas",
    "topics": [
      "CNN.",
      "Convolution.",
      "Pooling.",
      "RNN.",
      "LSTM.",
      "GRU.",
      "Attention.",
      "Embeddings.",
      "Representation learning."
    ],
    "projects": [],
    "code": "062"
  },
  {
    "id": 63,
    "name": "TRANSFORMERS",
    "title": "Arquitectura transformer",
    "topics": [
      "Tokens.",
      "Embeddings.",
      "Positional encoding.",
      "Query.",
      "Key.",
      "Value.",
      "Self-attention.",
      "Multi-head attention.",
      "Feed-forward networks.",
      "Residual connections.",
      "Layer normalization.",
      "Encoder.",
      "Decoder.",
      "Causal masking."
    ],
    "projects": [],
    "code": "063"
  },
  {
    "id": 64,
    "name": "LARGE LANGUAGE MODELS",
    "title": "LLM",
    "topics": [
      "Tokenization.",
      "Language modeling.",
      "Pretraining.",
      "Next-token prediction.",
      "Scaling.",
      "Inference.",
      "Sampling.",
      "Temperature.",
      "Top-k.",
      "Top-p.",
      "Context windows.",
      "KV cache.",
      "Fine-tuning.",
      "Instruction tuning.",
      "Preference optimization.",
      "RAG.",
      "Quantization.",
      "Distributed training."
    ],
    "projects": [
      "Crear un pequeño transformer.",
      "Entrenar un modelo pequeño propio."
    ],
    "code": "064"
  },
  {
    "id": 65,
    "name": "REINFORCEMENT LEARNING",
    "title": "Aprendizaje por interacción",
    "topics": [
      "Agent.",
      "Environment.",
      "State.",
      "Action.",
      "Reward.",
      "Policy.",
      "Value function.",
      "Bellman equations.",
      "Q-learning.",
      "Policy gradients.",
      "Actor-critic."
    ],
    "projects": [],
    "code": "065"
  },
  {
    "id": 66,
    "name": "MODELOS GENERATIVOS",
    "title": "Generación",
    "topics": [
      "Autoencoders.",
      "VAEs.",
      "GANs.",
      "Diffusion models.",
      "Score matching.",
      "Latent diffusion.",
      "Generación de imágenes."
    ],
    "projects": [],
    "code": "066"
  },
  {
    "id": 67,
    "name": "INGENIERÍA DEL SOFTWARE",
    "title": "Construcción profesional de sistemas",
    "topics": [
      "Modularidad.",
      "Abstracción.",
      "Encapsulación.",
      "APIs.",
      "Cohesión.",
      "Acoplamiento.",
      "Diseño de interfaces.",
      "Arquitecturas.",
      "Refactoring.",
      "Technical debt.",
      "Code review.",
      "Documentation."
    ],
    "projects": [],
    "code": "067"
  },
  {
    "id": 68,
    "name": "GIT",
    "title": "Control de versiones profundo",
    "topics": [
      "Repository.",
      "Working tree.",
      "Index.",
      "Commit.",
      "Blob.",
      "Tree.",
      "References.",
      "HEAD.",
      "Branches.",
      "Merge.",
      "Rebase.",
      "Cherry-pick.",
      "Tags.",
      "Remotes.",
      "Packfiles.",
      "Object database.",
      "Hashing.",
      "Internals de Git."
    ],
    "projects": [],
    "code": "068"
  },
  {
    "id": 69,
    "name": "TESTING",
    "title": "Verificación de software",
    "topics": [
      "Unit tests.",
      "Integration tests.",
      "System tests.",
      "Property-based testing.",
      "Fuzzing.",
      "Regression tests.",
      "Mocks.",
      "Test doubles.",
      "CI.",
      "Static analysis.",
      "Dynamic analysis."
    ],
    "projects": [],
    "code": "069"
  },
  {
    "id": 70,
    "name": "SISTEMAS DISTRIBUIDOS",
    "title": "Computadores que cooperan",
    "topics": [
      "Distributed systems.",
      "Replication.",
      "Partitioning.",
      "Consistency.",
      "Availability.",
      "CAP.",
      "Consensus.",
      "Raft.",
      "Distributed clocks.",
      "Lamport clocks.",
      "Fault tolerance.",
      "Leader election.",
      "Distributed databases.",
      "Message queues."
    ],
    "projects": [],
    "code": "070"
  },
  {
    "id": 71,
    "name": "BASES DE DATOS",
    "title": "Persistencia estructurada",
    "topics": [
      "Relational model.",
      "SQL.",
      "Tables.",
      "Indexes.",
      "B-trees.",
      "Transactions.",
      "ACID.",
      "Isolation.",
      "MVCC.",
      "Query planners.",
      "WAL.",
      "NoSQL.",
      "Key-value databases.",
      "Distributed databases."
    ],
    "projects": [],
    "code": "071"
  },
  {
    "id": 72,
    "name": "VIRTUALIZACIÓN Y CONTENEDORES",
    "title": "Máquinas dentro de máquinas",
    "topics": [
      "Virtual machines.",
      "Hypervisors.",
      "Hardware virtualization.",
      "Containers.",
      "Namespaces.",
      "cgroups.",
      "Docker internals.",
      "Images.",
      "Layers.",
      "Overlay filesystems."
    ],
    "projects": [],
    "code": "072"
  },
  {
    "id": 73,
    "name": "CLOUD Y SISTEMAS A GRAN ESCALA",
    "title": "Infraestructura moderna",
    "topics": [
      "Servers.",
      "Data centers.",
      "Virtualization.",
      "Containers.",
      "Orchestration.",
      "Kubernetes conceptualmente.",
      "Load balancers.",
      "Autoscaling.",
      "Fault tolerance.",
      "Observability.",
      "Distributed storage.",
      "Cloud networking."
    ],
    "projects": [],
    "code": "073"
  },
  {
    "id": 74,
    "name": "PERFORMANCE ENGINEERING",
    "title": "Hacer sistemas rápidos",
    "topics": [
      "Benchmarking.",
      "Profiling.",
      "CPU bottlenecks.",
      "Cache behaviour.",
      "Branch prediction.",
      "Memory bandwidth.",
      "SIMD.",
      "Multithreading.",
      "GPU acceleration.",
      "I/O.",
      "Latency.",
      "Throughput.",
      "Tail latency."
    ],
    "projects": [],
    "code": "074"
  },
  {
    "id": 75,
    "name": "LABORATORIO DE SISTEMAS REALES",
    "title": "¿Cómo funciona realmente...?",
    "topics": [
      "Almacenamiento interno.",
      "Objetos.",
      "DAG.",
      "Merge.",
      "Packfiles.",
      "Boot.",
      "Kernel.",
      "Procesos.",
      "Memoria.",
      "Drivers.",
      "Filesystems.",
      "Motor.",
      "BSP.",
      "Rendering.",
      "Fixed point.",
      "Game loop.",
      "WAD.",
      "Scene system.",
      "Rendering.",
      "Scripting.",
      "Physics.",
      "Engine source.",
      "Geometry.",
      "Mesh representation.",
      "Modifiers.",
      "Rendering.",
      "Cycles.",
      "GPU.",
      "Python API.",
      "NAND.",
      "Controller.",
      "FTL.",
      "Wear leveling.",
      "ECC.",
      "Pipeline.",
      "SIMT.",
      "Memory.",
      "Rasterization.",
      "Compute.",
      "Cable.",
      "ISP.",
      "Router.",
      "BGP.",
      "DNS.",
      "TCP.",
      "TLS.",
      "HTTP.",
      "CDN.",
      "Hardware.",
      "CPU.",
      "GPU.",
      "Memory.",
      "Operating system.",
      "APIs.",
      "Optimización.",
      "Tokens.",
      "Embeddings.",
      "Transformers.",
      "Attention.",
      "Training.",
      "Inference.",
      "GPUs.",
      "Distributed computing.",
      "Quantization.",
      "Sampling."
    ],
    "projects": [],
    "code": "075"
  },
  {
    "id": 76,
    "name": "HISTORIA DE LA COMPUTACIÓN",
    "title": "Cómo llegamos hasta aquí",
    "topics": [
      "Máquinas mecánicas.",
      "Pascal.",
      "Leibniz.",
      "Babbage.",
      "Ada Lovelace.",
      "Boole.",
      "Turing.",
      "Shannon.",
      "Von Neumann.",
      "Relés.",
      "Tubos de vacío.",
      "Transistor.",
      "Circuito integrado.",
      "Microprocesador.",
      "Mainframes.",
      "Minicomputers.",
      "Microcomputers.",
      "Unix.",
      "Internet.",
      "PC.",
      "Consolas.",
      "GPU.",
      "Smartphone.",
      "Cloud.",
      "IA moderna."
    ],
    "projects": [],
    "code": "076"
  },
  {
    "id": 77,
    "name": "FILOSOFÍA Y METODOLOGÍA DE INGENIERÍA",
    "title": "Pensar como ingeniera",
    "topics": [
      "Modelar problemas.",
      "Separar abstracción e implementación.",
      "Identificar supuestos.",
      "Diseñar experimentos.",
      "Medir.",
      "Comparar alternativas.",
      "Analizar trade-offs.",
      "Identificar límites.",
      "Leer documentación.",
      "Leer estándares.",
      "Leer papers.",
      "Leer código fuente.",
      "Reverse engineering conceptual.",
      "Debugging sistemático.",
      "Documentación técnica.",
      "Diseño incremental.",
      "Validación.",
      "Reproducibilidad."
    ],
    "projects": [],
    "code": "077"
  },
  {
    "id": 78,
    "name": "PROYECTOS DE INTEGRACIÓN",
    "title": "",
    "topics": [
      "Crear un sistema de codificación.",
      "Calculadora binaria.",
      "Simulador eléctrico.",
      "Puertas lógicas.",
      "ALU.",
      "CPU educativa.",
      "Programas assembly.",
      "Emulador.",
      "Allocator.",
      "Shell.",
      "Lenguaje propio.",
      "Compilador.",
      "Sistema de archivos.",
      "Kernel educativo.",
      "Servidor HTTP.",
      "DNS simplificado.",
      "Analizador de tráfico.",
      "Laboratorios de vulnerabilidades.",
      "Reverse engineering de programas.",
      "Renderer 3D.",
      "Motor gráfico.",
      "Videojuego completo.",
      "Sintetizador procedural.",
      "Demo demoscene.",
      "Intro 64 KB.",
      "Proyecto STM32.",
      "Diseño FPGA.",
      "PCB.",
      "Red neuronal desde cero.",
      "Transformer pequeño.",
      "Modelo propio.",
      "Sistema distribuido pequeño.",
      "Proyecto final multidisciplinar.",
      "hardware o emulación de hardware;",
      "programación de bajo nivel;",
      "sistema operativo o runtime;",
      "gráficos;",
      "networking;",
      "seguridad;",
      "herramientas propias;",
      "contenido procedural;",
      "inteligencia artificial."
    ],
    "projects": []
  }
];


/**
 * Áreas de aprendizaje orientadas a objetivos.
 * Un bloque puede pertenecer a varias áreas deliberadamente: la computación
 * real tiene prerrequisitos compartidos y fronteras menos limpias que un menú.
 */
window.GOAL_AREAS = [
  {
    "id": "demoscene",
    "name": "Demoscene",
    "subtitle": "Especialmente Future Crew",
    "description": "De cómo se representan bits y señales a gráficos, shaders, audio procedural, sizecoding y la cultura demoscene.",
    "blocks": [
      1,
      2,
      5,
      7,
      8,
      9,
      10,
      11,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      43,
      46,
      47,
      48,
      49,
      50,
      51,
      57,
      74,
      75,
      76,
      77,
      78
    ],
    "focus": [
      47,
      48,
      49,
      50,
      51
    ],
    "badge": "Future Crew → técnica + cultura"
  },
  {
    "id": "cyber",
    "name": "Ciberseguridad",
    "subtitle": "OverTheWire · actualmente Natas",
    "description": "Web, Linux, redes, criptografía, explotación binaria, reversing y forense con una ruta defensiva y de laboratorio.",
    "blocks": [
      1,
      2,
      9,
      10,
      11,
      12,
      13,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      57,
      59,
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      77,
      78
    ],
    "focus": [
      21,
      22,
      23,
      24,
      25,
      26,
      27
    ],
    "badge": "Natas → web → sistemas"
  },
  {
    "id": "computers",
    "name": "Cómo funcionan realmente los ordenadores",
    "subtitle": "De electrones a procesos",
    "description": "La ruta vertical de materia, lógica y CPU hasta compiladores, kernel, drivers, memoria y sistemas reales.",
    "blocks": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
      59,
      67,
      68,
      69,
      72,
      74,
      75,
      76,
      77,
      78
    ],
    "focus": [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      12,
      14,
      15
    ],
    "badge": "electrón → CPU → kernel"
  },
  {
    "id": "gamedev",
    "name": "Desarrollo de videojuegos",
    "subtitle": "Engine, física, IA, audio y red",
    "description": "Matemáticas y gráficos hasta arquitectura de engine, física, animación, IA, audio, multijugador y producción.",
    "blocks": [
      2,
      9,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      50,
      57,
      59,
      67,
      68,
      69,
      74,
      75,
      77,
      78
    ],
    "focus": [
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45
    ],
    "badge": "renderer → engine → juego"
  },
  {
    "id": "godot",
    "name": "Godot",
    "subtitle": "Del uso al engine source",
    "description": "Ruta práctica hacia Godot apoyada en arquitectura de videojuegos, gráficos, física, audio, networking y herramientas de editor.",
    "blocks": [
      9,
      11,
      28,
      29,
      30,
      31,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      57,
      59,
      67,
      69,
      74,
      75,
      77,
      78
    ],
    "focus": [
      39,
      40,
      41,
      42,
      43,
      44,
      45
    ],
    "badge": "GDScript/C# → engine internals"
  },
  {
    "id": "pixelart",
    "name": "Pixel art y arte técnico",
    "subtitle": "Imagen discreta + pipeline",
    "description": "Color, sampling, raster, shaders y herramientas hasta pixel clusters, dithering, sprites, tiles y procedural pixel art.",
    "blocks": [
      2,
      28,
      29,
      33,
      34,
      35,
      36,
      37,
      38,
      41,
      46,
      48,
      50,
      57,
      74,
      75,
      77,
      78
    ],
    "focus": [
      34,
      36,
      37,
      41,
      46,
      48,
      50
    ],
    "badge": "píxel → shader → dirección artística"
  },
  {
    "id": "electronics",
    "name": "Electrónica",
    "subtitle": "Circuitos, MCU, FPGA y PCB",
    "description": "Electricidad y semiconductores hasta analógica, microcontroladores, RTOS, FPGA, integridad de señal y fabricación de PCB.",
    "blocks": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      14,
      16,
      33,
      52,
      53,
      54,
      55,
      56,
      74,
      75,
      76,
      77,
      78
    ],
    "focus": [
      3,
      4,
      52,
      53,
      54,
      55,
      56
    ],
    "badge": "voltaje → firmware → placa"
  },
  {
    "id": "ai",
    "name": "Inteligencia artificial",
    "subtitle": "De matemáticas a modelos generativos",
    "description": "Álgebra, cálculo, probabilidad y optimización hasta redes neuronales, transformers, LLM, RL y diffusion.",
    "blocks": [
      1,
      2,
      28,
      29,
      30,
      31,
      32,
      33,
      35,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66,
      67,
      69,
      70,
      74,
      75,
      77,
      78
    ],
    "focus": [
      29,
      30,
      31,
      32,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ],
    "badge": "matrices → training → inference"
  },
  {
    "id": "os",
    "name": "Sistemas operativos",
    "subtitle": "Kernel, Linux, drivers y virtualización",
    "description": "Arquitectura, C y concurrencia hasta procesos, memoria, filesystems, drivers, Linux interno, contenedores y observabilidad.",
    "blocks": [
      2,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      53,
      54,
      57,
      58,
      59,
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76,
      77,
      78
    ],
    "focus": [
      5,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      59,
      72
    ],
    "badge": "ISA → syscall → kernel"
  },
  {
    "id": "networks",
    "name": "Redes e Internet",
    "subtitle": "Del medio físico a sistemas distribuidos",
    "description": "Señales, Ethernet, IP, routing, TCP/QUIC y HTTP hasta networking de juegos, sistemas distribuidos, cloud y observabilidad.",
    "blocks": [
      1,
      2,
      12,
      14,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      33,
      44,
      59,
      67,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      77,
      78
    ],
    "focus": [
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      44,
      70,
      73
    ],
    "badge": "señal → BGP → HTTP → cloud"
  }
];
